### ISSUE TITLE
Atmosphere recipes

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/CMIP7-Hackathon#1]
I have selected the `clouds/recipe_clouds_bias.yml` and the `clouds/recipe_clouds_ipcc.yml`

I have split the `clouds/recipe_clouds_bias.yml` one into 3 separate diagnostics for precipitation, clouds and temperature

Now what we need for the workshop:

Make it work for ACCESS-ESM1-5 CMIP6 outputs.
The recipes use model means so we also need a couple more models from the replicas on gadi. UKESM, CESM?

The idea is to have recipes that take less than 5 mins to run.

Strategies for that include:
- reduced time range
- reduced number of datasets
- reduced number of diagnostics
- change resolution of the grid

I think it would also be a good idea to document the recipes with comments, to make it very clear what each sections are about....

**Comment by rbeucher** [comment]
@flicj191 happy to give it a try?

**Comment by flicj191** [comment]
I can't self assign or create a branch, should we have write access?

**Comment by rbeucher** [comment]
fixed!

**Comment by flicj191** [comment]
An issue with running as is in *recipe_clouds_bias_precip.yml*
The observational dataset used: `{dataset: GPCP-V2.2, project: obs4MIPs, level: L3, start_year: 1986, end_year: 2005, tier: 1}` can't be found in *ct11* because its in a version folder instead of a level up in the dataset folder:
`ls /g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-V2.2/v20180518/`
*pr_GPCP-SG_L3_v2.2_197901-201312.nc*
should be in `/g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2/Tier1/GPCP-V2.2` to find it

**Comment by rbeucher** [comment]
Does it work if you add the version facet in the recipe?

**Comment by flicj191** [comment]
I can try but I don't really think so, it downloaded fine on *copyq* and it worked if i added the version to the path in *config-developer.yml*
```
obs4MIPs:
  cmor_strict: false
  input_dir:
    default: 'Tier{tier}/{dataset}' ##add version
    ESGF: '{project}/{dataset}/{version}' 
    ..
 ```
 it uses default

**Comment by rbeucher** [comment]
If the file location breaks the pattern, we should have it move. Maybe create an issue and ask Jo if it can be moved?
